downsample: 5
dropout: 0.0
epochs: 500
eval: 0
lr: 0.001
max_grad_norm: 0.1
mlp_ratio: 1
n_heads: 4
n_hidden: 64
n_layers: 4
ntrain: 400
out_dim: 4
ref: 8
slice_num: 16
space_dim: 7
unified_pos: 0
weight_decay: 0.0001
