"""Controlled taxonomy of diagnostic failure mechanisms."""

from enum import Enum


class FailureMechanism(str, Enum):
    SURROGATE_DOMAIN_RISK = "SURROGATE_DOMAIN_RISK"
    PARAM_BOUNDARY_COLLAPSE = "PARAM_BOUNDARY_COLLAPSE"
    NORM_STATS_STYLE_MISMATCH = "NORM_STATS_STYLE_MISMATCH"
    MISSING_REQUIRED_ARTIFACT = "MISSING_REQUIRED_ARTIFACT"
    METRICS_NUMERICAL_SANITY_FAILURE = "METRICS_NUMERICAL_SANITY_FAILURE"
    GEOMETRY_DEFORMATION_EXCESSIVE = "GEOMETRY_DEFORMATION_EXCESSIVE"
    MESH_QUALITY_RISK = "MESH_QUALITY_RISK"
    FLOW_FIELD_INCONSISTENT = "FLOW_FIELD_INCONSISTENT"
    DRAG_DECOMPOSITION_INCONSISTENT = "DRAG_DECOMPOSITION_INCONSISTENT"
    AERO_PLAUSIBILITY_WEAK = "AERO_PLAUSIBILITY_WEAK"
    VISUAL_EVIDENCE_MISSING = "VISUAL_EVIDENCE_MISSING"
    SIMULATION_FAILURE = "SIMULATION_FAILURE"
    OTHER = "OTHER"


ALL_FAILURE_MECHANISMS = [m.value for m in FailureMechanism]
