"""Controlled mitigation actions for diagnostic recommendations."""

from enum import Enum


class MitigationAction(str, Enum):
    TIGHTEN_PARAMETER_BOUNDS = "TIGHTEN_PARAMETER_BOUNDS"
    ENFORCE_STYLE_NORM_COMPATIBILITY = "ENFORCE_STYLE_NORM_COMPATIBILITY"
    ENFORCE_REQUIRED_ARTIFACTS = "ENFORCE_REQUIRED_ARTIFACTS"
    ADD_GEOMETRY_REGULARIZATION = "ADD_GEOMETRY_REGULARIZATION"
    ADD_MESH_QUALITY_SCREENING = "ADD_MESH_QUALITY_SCREENING"
    ADD_FLOW_CONSISTENCY_CHECKS = "ADD_FLOW_CONSISTENCY_CHECKS"
    ADD_PHYSICS_CONSISTENCY_PENALTY = "ADD_PHYSICS_CONSISTENCY_PENALTY"
    RENDER_FLOW_IMAGES_FOR_DIAGNOSTICS = "RENDER_FLOW_IMAGES_FOR_DIAGNOSTICS"
    ADD_POSTHOC_CFD_VALIDATION = "ADD_POSTHOC_CFD_VALIDATION"
    REWEIGHT_OBJECTIVE_TERMS = "REWEIGHT_OBJECTIVE_TERMS"
    REJECT_OOD_CANDIDATES = "REJECT_OOD_CANDIDATES"
    OTHER = "OTHER"


ALL_MITIGATION_ACTIONS = [m.value for m in MitigationAction]
