#!/usr/bin/env python3
"""
3D surface panel plot: best designs per method per DrivAer body variant.

Layout: 3 rows (body E / F / N) × 3 cols (Baseline / v3-best / BO-best).
Each cell shows the car surface coloured by the z-component of the outward
surface normal (blue = downward-facing, red = upward-facing), which gives a
clean geometric reading without requiring CFD solution data.

Geometry is generated by applying saved FFD design parameters to the base VTK
mesh via mesh_generator.deform_vtk().  No CFD re-run is needed.

Output:
    environments/DrivAer_Star/results/best_design_panels/
        drivaer_best_designs_panel.pdf / .png
        drivaer_best_designs_{body}_{method}.png   (individual renders)

Usage:
    python analysis/plot_drivaer_best_designs.py
"""

import json
import os
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pyvista as pv

import importlib.util
_mg_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "environments", "DrivAer_Star", "mesh_generator.py")
_spec = importlib.util.spec_from_file_location("mesh_generator", _mg_path)
_mg   = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mg)
deform_vtk = _mg.deform_vtk

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE    = os.path.join(REPO, "environments", "DrivAer_Star", "results")
OUT_DIR = os.path.join(BASE, "analysis_plots_cd_cl_constrained")
os.makedirs(OUT_DIR, exist_ok=True)

BASE_VTK = {
    "E": os.path.join(REPO, "environments", "DrivAer_Star", "data", "vtk_E", "00000.vtk"),
    "F": os.path.join(REPO, "environments", "DrivAer_Star", "data", "vtk_F", "00000.vtk"),
    "N": os.path.join(REPO, "environments", "DrivAer_Star", "data", "vtk_N", "00001.vtk"),
}

BODIES  = ["E", "F", "N"]
METHODS = ["Baseline", "ShapeEvolve", "Bayesian Opt. (exact GP)"]

STYLE = {
    "font.family": "serif",
    "font.serif": ["Times New Roman", "DejaVu Serif", "serif"],
    "mathtext.fontset": "cm",
    "font.size": 9,
    "axes.labelsize": 10,
    "axes.titlesize": 10,
    "figure.dpi": 200,
}

# ── Identify best designs ─────────────────────────────────────────────────────

def best_design_from_runs(run_dirs):
    """Return (design_dir, Cd, reward) for the best design across all run_dirs."""
    best_reward = float("-inf")
    best_design_path = None
    best_cd = None
    for run_dir in run_dirs:
        csv = os.path.join(run_dir, "results_recovered.csv")
        if not os.path.exists(csv):
            continue
        with open(csv) as f:
            import csv as csv_mod
            rows = list(csv_mod.DictReader(f))
        if not rows:
            continue
        row = max(rows, key=lambda r: float(r["reward"]))
        reward = float(row["reward"])
        if reward > best_reward:
            best_reward = reward
            design_name = row["design"]
            best_design_path = os.path.join(run_dir, design_name, "save", "results.json")
            best_cd = float(row["Cd"])
    return best_design_path, best_cd, best_reward


def load_params(results_json_path):
    with open(results_json_path) as f:
        d = json.load(f)
    return d["design"]


# ── Rendering ─────────────────────────────────────────────────────────────────

pv.OFF_SCREEN = True


def render_mesh(mesh, out_path, window_size=(900, 500)):
    """Render car surface coloured by normal z-component, isometric 3/4 view."""
    normals_z = mesh.cell_data["Normals"][:, 2]
    mesh.cell_data["nz"] = normals_z

    pl = pv.Plotter(off_screen=True, window_size=window_size)
    pl.set_background("white")
    pl.add_mesh(
        mesh,
        scalars="nz",
        cmap="RdBu",
        clim=[-1.0, 1.0],
        show_scalar_bar=False,
        lighting=True,
        smooth_shading=False,
        ambient=0.3,
        diffuse=0.7,
        specular=0.2,
    )

    # 3/4 front-left isometric view: position camera above-left-front
    bounds = mesh.bounds   # (xmin,xmax, ymin,ymax, zmin,zmax)
    cx = (bounds[0] + bounds[1]) / 2
    cy = (bounds[2] + bounds[3]) / 2
    cz = (bounds[4] + bounds[5]) / 2
    xlen = bounds[1] - bounds[0]

    pl.camera.focal_point = (cx, cy, cz + 0.05)
    pl.camera.position = (
        bounds[0] - xlen * 0.55,   # in front
        bounds[2] - xlen * 0.60,   # to the left
        bounds[5] + xlen * 0.45,   # above
    )
    pl.camera.up = (0, 0, 1)

    img = pl.screenshot(out_path, return_img=True)
    pl.close()
    return img


def render_baseline(body, out_path):
    """Render the undeformed base mesh (identity params)."""
    PARAM_KEYS = _mg.PARAM_KEYS
    BOUNDS     = _mg.BOUNDS
    params = {k: (BOUNDS[k][0] + BOUNDS[k][1]) / 2 for k in PARAM_KEYS}
    mesh = deform_vtk(BASE_VTK[body], params)
    return render_mesh(mesh, out_path)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    plt.rcParams.update(STYLE)

    # Collect meshes and metadata
    renders = {}   # (body, method) -> (img_array, label)

    for body in BODIES:
        print(f"\n=== Body {body} ===")

        # Baseline
        bp = os.path.join(OUT_DIR, f"DrivAer_Star_3d_panel_best_designs_vtk_{body}_baseline_cd_cl_constrained.png")
        img = render_baseline(body, bp)
        renders[(body, "Baseline")] = (img, f"Baseline\n(undeformed)")
        print(f"  Baseline rendered")

        # v3 best
        v3_dirs = [
            os.path.join(BASE, f"run_v3_dynamic_optimizer_cd_cl_constrained_"
                               f"drivaer_star_vtk_{body}_attempt_{a}_flash_2_5_n6000")
            for a in range(1, 11)
        ]
        rj, cd, reward = best_design_from_runs(v3_dirs)
        if rj and os.path.exists(rj):
            params = load_params(rj)
            mesh   = deform_vtk(BASE_VTK[body], params)
            op     = os.path.join(OUT_DIR, f"DrivAer_Star_3d_panel_best_designs_vtk_{body}_v3_cd_cl_constrained.png")
            img    = render_mesh(mesh, op)
            renders[(body, "ShapeEvolve")] = (
                img, f"ShapeEvolve\n$C_d$={cd:.4f}  r={reward:.4f}")
            print(f"  v3 best: Cd={cd:.4f}, reward={reward:.4f}")
        else:
            print(f"  v3: no valid design found")

        # BO best
        bo_dirs = [
            os.path.join(BASE, f"run_BO_torch_cd_cl_constrained_vtk_{body}_seed{s}_n1000")
            for s in range(10)
        ]
        rj, cd, reward = best_design_from_runs(bo_dirs)
        if rj and os.path.exists(rj):
            params = load_params(rj)
            mesh   = deform_vtk(BASE_VTK[body], params)
            op     = os.path.join(OUT_DIR, f"DrivAer_Star_3d_panel_best_designs_vtk_{body}_bo_cd_cl_constrained.png")
            img    = render_mesh(mesh, op)
            renders[(body, "Bayesian Opt. (exact GP)")] = (
                img, f"Bayesian Opt.\n$C_d$={cd:.4f}  r={reward:.4f}")
            print(f"  BO best: Cd={cd:.4f}, reward={reward:.4f}")
        else:
            print(f"  BO: no valid design found")

    # ── Assemble panel ────────────────────────────────────────────────────────
    fig, axes = plt.subplots(
        len(BODIES), len(METHODS),
        figsize=(12, 5.5),
        facecolor="white",
    )
    fig.subplots_adjust(hspace=0.05, wspace=0.03, top=0.93, bottom=0.02,
                        left=0.06, right=0.99)

    BODY_LABELS = {"E": "Estate", "F": "Fastback", "N": "Notchback"}

    for row, body in enumerate(BODIES):
        for col, method in enumerate(METHODS):
            ax = axes[row][col]
            key = (body, method)
            if key in renders:
                img, label = renders[key]
                ax.imshow(img)
                # Method label on top row only
                if row == 0:
                    ax.set_title(method, fontsize=9, pad=4)
            ax.axis("off")
            # Body label on left column only
            if col == 0:
                ax.set_ylabel(BODY_LABELS[body], fontsize=9, labelpad=4,
                              rotation=90, va="center")
                ax.yaxis.set_label_coords(-0.02, 0.5)

    fig.suptitle(
        r"DrivAer$^\star$ $C_d$-constrained optimisation — best designs per method",
        fontsize=10, fontweight="medium", y=0.97,
    )

    # Colourbar legend (normal z: blue=down, red=up)
    sm = plt.cm.ScalarMappable(cmap="RdBu", norm=plt.Normalize(-1, 1))
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes, orientation="vertical",
                        fraction=0.012, pad=0.01, shrink=0.6)
    cbar.set_label("Surface normal $n_z$", fontsize=8)
    cbar.set_ticks([-1, 0, 1])
    cbar.set_ticklabels(["down", "0", "up"], fontsize=7)

    for ext in (".pdf", ".png"):
        out = os.path.join(OUT_DIR, f"DrivAer_Star_3d_panel_best_designs_cd_cl_constrained{ext}")
        fig.savefig(out, dpi=200, bbox_inches="tight")
        print(f"\nSaved: {out}")
    plt.close(fig)


if __name__ == "__main__":
    main()
